// SPDX-License-Identifier: LicenseRef-TTZip-Source-Available-1.0
//
// Copyright (c) 2026 Witt Kung <witt.w.kung@gmail.com>
// All rights reserved.
//
// TTZip: High-performance native archiving and compression engine for macOS.

import Foundation

/// Threat assessment report generated by the security scanning engine.
public struct SecurityScanResult: Sendable {
    public let isSafe: Bool
    public let suspiciousFileNames: [String]
    public let detailMessage: String
}

/// Security risk classification levels.
public enum SecurityRiskLevel: String, Sendable, Codable, Comparable {
    case safe = "SAFE"
    case warning = "WARNING"
    case critical = "CRITICAL"
    
    private var severity: Int {
        switch self {
        case .safe: return 0
        case .warning: return 1
        case .critical: return 2
        }
    }
    
    public static func < (lhs: SecurityRiskLevel, rhs: SecurityRiskLevel) -> Bool {
        return lhs.severity < rhs.severity
    }
}

/// Unified archive security audit report.
public struct SecurityReport: Sendable, Equatable {
    public let isSafe: Bool
    public let suspiciousFileNames: [String]
    public let hasZipSlipRisk: Bool
    public let detailMessage: String
    public let riskLevel: SecurityRiskLevel
    
    public init(
        isSafe: Bool,
        suspiciousFileNames: [String],
        hasZipSlipRisk: Bool,
        detailMessage: String,
        riskLevel: SecurityRiskLevel
    ) {
        self.isSafe = isSafe
        self.suspiciousFileNames = suspiciousFileNames
        self.hasZipSlipRisk = hasZipSlipRisk
        self.detailMessage = detailMessage
        self.riskLevel = riskLevel
    }
}

/// In-memory threat and vulnerability scanning engine (Zip Slip, dangerous extensions, and traversal checks).
public final class SecurityScanner: @unchecked Sendable {
    public static let shared = SecurityScanner()
    
    private let dangerousExtensions: Set<String> = [
        "exe", "bat", "cmd", "vbs", "js", "scr", "pif", "sh", "command"
    ]
    
    private init() {}
    
    /// Asserts whether a path is free of Zip Slip traversal (`..`), absolute prefixes, or reserved characters.
    public static func isPathSafe(_ path: String) -> Bool {
        guard !path.isEmpty else { return false }
        if path.contains("\0") { return false }
        let res = PlatformPathSanitizer.sanitize(path: path)
        if res.hasTraversalAttack || res.isAbsolute || res.isUNCPath || res.containsWindowsReservedDeviceName || res.strippedAlternateDataStream != nil {
            return false
        }
        return !res.normalizedPath.isEmpty
    }
    
    /// Normalizes and cleanses a path across platforms.
    public static func sanitizePath(_ path: String) -> String? {
        let res = PlatformPathSanitizer.sanitize(path: path)
        guard !res.normalizedPath.isEmpty else { return nil }
        return res.normalizedPath
    }

    /// Scans an array of `ArchiveEntry` items for executable scripts or Zip Slip threats.
    public func scanArchiveEntries(_ entries: [ArchiveEntry]) -> SecurityScanResult {
        var suspicious: [String] = []
        for entry in entries {
            // Zip Slip path traversal check
            if !Self.isPathSafe(entry.path) {
                if !suspicious.contains(entry.path) {
                    suspicious.append(entry.path)
                }
                continue
            }
            
            let ext = (entry.name as NSString).pathExtension.lowercased()
            if dangerousExtensions.contains(ext) {
                if !suspicious.contains(entry.path) {
                    suspicious.append(entry.path)
                }
                continue
            }
        }
        if suspicious.isEmpty {
            return SecurityScanResult(
                isSafe: true,
                suspiciousFileNames: [],
                detailMessage: "Memory scan clean: No malicious extensions or path traversal threats detected"
            )
        } else {
            return SecurityScanResult(
                isSafe: false,
                suspiciousFileNames: suspicious,
                detailMessage: "Security warning: Detected \(suspicious.count) potentially suspicious files or paths"
            )
        }
    }

    /// Scans entries and constructs a unified `SecurityReport`.
    public func scanEntriesForReport(_ entries: [ArchiveEntry]) -> SecurityReport {
        let rawScan = scanArchiveEntries(entries)
        var hasZipSlip = false
        
        for entry in entries {
            let p = entry.path.lowercased()
            if p.contains("..") || p.hasPrefix("/") || p.contains(":\\") || !Self.isPathSafe(entry.path) {
                hasZipSlip = true
                break
            }
        }
        
        let riskLevel: SecurityRiskLevel
        if hasZipSlip {
            riskLevel = .critical
        } else if !rawScan.isSafe {
            riskLevel = .warning
        } else {
            riskLevel = .safe
        }
        
        var message = rawScan.detailMessage
        if hasZipSlip {
            message = "Critical security alert: Zip Slip path traversal vulnerability detected!"
        }
        
        return SecurityReport(
            isSafe: rawScan.isSafe && !hasZipSlip,
            suspiciousFileNames: rawScan.suspiciousFileNames,
            hasZipSlipRisk: hasZipSlip,
            detailMessage: message,
            riskLevel: riskLevel
        )
    }

    /// Scans a composite component tree.
    public func scanComponent(_ component: ArchiveComponentProtocol) -> SecurityScanResult {
        var suspicious: [String] = []
        for leaf in component.flattenLeaves() {
            let path = leaf.path
            let lowerPath = path.lowercased()
            if lowerPath.contains("..") || lowerPath.hasPrefix("/") || !Self.isPathSafe(path) {
                if !suspicious.contains(path) {
                    suspicious.append(path)
                }
                continue
            }
            
            let ext = (leaf.name as NSString).pathExtension.lowercased()
            if dangerousExtensions.contains(ext) {
                if !suspicious.contains(path) {
                    suspicious.append(path)
                }
                continue
            }
            
            if let compressedSize = leaf.compressedSizeBytes, compressedSize > 0 {
                let ratio = Double(leaf.sizeBytes) / Double(compressedSize)
                if ratio > 100.0 && leaf.sizeBytes > 1_000_000 {
                    if !suspicious.contains(path) {
                        suspicious.append(path)
                    }
                }
            }
        }
        
        if suspicious.isEmpty {
            return SecurityScanResult(
                isSafe: true,
                suspiciousFileNames: [],
                detailMessage: "Memory scan clean: No malicious extensions or path traversal threats detected"
            )
        } else {
            return SecurityScanResult(
                isSafe: false,
                suspiciousFileNames: suspicious,
                detailMessage: "Security warning: Detected \(suspicious.count) potentially suspicious files or paths"
            )
        }
    }
    
    public func scanComponents(_ components: [ArchiveComponentProtocol]) -> SecurityScanResult {
        var suspicious: [String] = []
        for component in components {
            let res = scanComponent(component)
            if !res.isSafe {
                for item in res.suspiciousFileNames {
                    if !suspicious.contains(item) {
                        suspicious.append(item)
                    }
                }
            }
        }
        
        if suspicious.isEmpty {
            return SecurityScanResult(
                isSafe: true,
                suspiciousFileNames: [],
                detailMessage: "Memory scan clean: No malicious extensions or path traversal threats detected"
            )
        } else {
            return SecurityScanResult(
                isSafe: false,
                suspiciousFileNames: suspicious,
                detailMessage: "Security warning: Detected \(suspicious.count) potentially suspicious files or paths"
            )
        }
    }
}
