// SPDX-License-Identifier: LicenseRef-TTZip-Source-Available-1.0
//
// Copyright (c) 2026 Witt Kung <witt.w.kung@gmail.com>
// All rights reserved.
//
// TTZip: High-performance native archiving and compression engine for macOS.
// Auto-generated by cbindgen / TTZip build pipeline. DO NOT EDIT DIRECTLY.

#ifndef TTZIP_RUST_GLUE_H
#define TTZIP_RUST_GLUE_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifdef TTZIP_STATUS_OK
#undef TTZIP_STATUS_OK
#endif
#ifdef TTZIP_STATUS_EOF
#undef TTZIP_STATUS_EOF
#endif

#ifdef __cplusplus
extern "C" {
#endif

typedef enum TTZipStatus {
    TTZIP_STATUS_OK = 0,
    TTZIP_STATUS_EOF = 1,
    TTZIP_STATUS_CANCELLED = 2,
    TTZIP_STATUS_ERR_INVALID_PARAM = -1,
    TTZIP_STATUS_ERR_FILE_NOT_FOUND = -2,
    TTZIP_STATUS_ERR_MMAP_FAILED = -3,
    TTZIP_STATUS_ERR_CORRUPT_HEADER = -4,
    TTZIP_STATUS_ERR_INVALID_OFFSET = -5,
    TTZIP_STATUS_ERR_ARCHIVE_INIT_FAILED = -6,
    TTZIP_STATUS_ERR_OPEN_FAILED = -7,
    TTZIP_STATUS_ERR_PATH_TOO_LONG = -8,
    TTZIP_STATUS_ERR_OUT_OF_MEMORY = -9,
    TTZIP_STATUS_ERR_INVALID_PASSWORD = -10,
    TTZIP_STATUS_ERR_EXTRACTION_FAILED = -11,
    TTZIP_STATUS_ERR_COMPRESSION_FAILED = -12,
    TTZIP_STATUS_ERR_SECURITY_VIOLATION = -30,
    TTZIP_STATUS_ERR_PANIC_CAUGHT = -99
} TTZipStatus;

typedef enum TTZipArchiveFormat {
    TTZIP_ARCHIVE_FORMAT_AUTO = 0,
    TTZIP_ARCHIVE_FORMAT_ZIP = 1,
    TTZIP_ARCHIVE_FORMAT_SEVEN_ZIP = 2,
    TTZIP_ARCHIVE_FORMAT_TAR = 3,
    TTZIP_ARCHIVE_FORMAT_TAR_GZ = 4,
    TTZIP_ARCHIVE_FORMAT_TAR_BZ2 = 5,
    TTZIP_ARCHIVE_FORMAT_TAR_XZ = 6,
    TTZIP_ARCHIVE_FORMAT_TAR_ZSTD = 7,
    TTZIP_ARCHIVE_FORMAT_DMG = 8,
    TTZIP_ARCHIVE_FORMAT_LZFSE = 9,
    TTZIP_ARCHIVE_FORMAT_SNAPPY = 10,
    TTZIP_ARCHIVE_FORMAT_UNKNOWN = 99
} TTZipArchiveFormat;

typedef enum TTZipCompressionLevel {
    TTZIP_COMPRESSION_LEVEL_STORE = 0,
    TTZIP_COMPRESSION_LEVEL_FASTEST = 1,
    TTZIP_COMPRESSION_LEVEL_FAST = 3,
    TTZIP_COMPRESSION_LEVEL_NORMAL = 6,
    TTZIP_COMPRESSION_LEVEL_MAXIMUM = 9,
    TTZIP_COMPRESSION_LEVEL_ULTRA = 12
} TTZipCompressionLevel;

typedef enum TTZipEncryptionMethod {
    TTZIP_ENCRYPTION_NONE = 0,
    TTZIP_ENCRYPTION_ZIP_CRYPTO = 1,
    TTZIP_ENCRYPTION_AES128 = 2,
    TTZIP_ENCRYPTION_AES192 = 3,
    TTZIP_ENCRYPTION_AES256 = 4
} TTZipEncryptionMethod;

typedef enum TTZipLogLevel {
    TTZIP_LOG_LEVEL_DEBUG = 0,
    TTZIP_LOG_LEVEL_INFO = 1,
    TTZIP_LOG_LEVEL_WARNING = 2,
    TTZIP_LOG_LEVEL_ERROR = 3
} TTZipLogLevel;

typedef struct TTZipEntryMetadata {
    const char *path;
    uint64_t uncompressed_size;
    uint64_t compressed_size;
    uint32_t crc32;
    int64_t mtime_epoch_secs;
    uint32_t mode;
    bool is_directory;
    bool is_encrypted;
    uint16_t compression_method;
} TTZipEntryMetadata;

typedef bool (*TTZipProgressCallback)(uint64_t processed_bytes, uint64_t total_bytes, const char *current_entry, void *user_data);
typedef bool (*TTZipInspectCallback)(const TTZipEntryMetadata *entry, void *user_data);

typedef struct TTZipExtractOptions {
    const char *destination_path;
    const char *password;
    uint32_t thread_budget;
    bool overwrite_existing;
    bool preserve_permissions;
    bool dry_run;
    TTZipProgressCallback progress_callback;
    void *user_data;
} TTZipExtractOptions;

typedef struct TTZipCreateOptions {
    TTZipArchiveFormat format;
    TTZipCompressionLevel level;
    TTZipEncryptionMethod encryption;
    const char *password;
    uint32_t thread_budget;
    uint32_t solid_block_size_mb;
    TTZipProgressCallback progress_callback;
    void *user_data;
} TTZipCreateOptions;

typedef struct TTZipAes256Context {
    uint8_t key[32];
    uint8_t iv_or_counter[16];
    uint8_t round_keys_enc[240];
    uint8_t round_keys_dec[240];
} TTZipAes256Context;

/**
 * Version and Lifecycle
 */
const char *ttzip_rust_version(void);
TTZipStatus ttzip_rust_init(void);
const char *ttzip_rust_status_string(TTZipStatus status);
bool ttzip_rust_is_hardware_accelerated(void);

/**
 * Checksum & SIMD operations
 */
uint32_t ttzip_rust_crc32(uint32_t crc, const uint8_t *data, size_t len);
uint32_t ttzip_rust_adler32(uint32_t adler, const uint8_t *data, size_t len);

/**
 * AES-256 & ZipCrypto Crypto operations
 */
int32_t ttzip_rust_aes256_ctr(const uint8_t *key, uint64_t initial_counter, const uint8_t *src, size_t len, uint8_t *dst);
int32_t ttzip_rust_aes256_cbc_decrypt(const uint8_t *key, const uint8_t *iv, const uint8_t *src, size_t len, uint8_t *dst);
int32_t ttzip_rust_7z_kdf_sha256(const char *password, const uint8_t *salt, size_t salt_len, uint32_t num_cycles_power, uint8_t *out_key);
int32_t ttzip_rust_zipcrypto_init_keys(const char *password, uint32_t *key0, uint32_t *key1, uint32_t *key2);
int32_t ttzip_rust_zipcrypto_decrypt_stream(uint32_t *key0, uint32_t *key1, uint32_t *key2, const uint8_t *src, size_t len, uint8_t *dst);
int32_t ttzip_rust_zipcrypto_encrypt_stream(uint32_t *key0, uint32_t *key1, uint32_t *key2, const uint8_t *src, size_t len, uint8_t *dst);

/**
 * Reed-Solomon FEC & Self-Healing operations
 */
int32_t ttzip_rust_rs_encode(const uint8_t *const *data_ptrs, size_t k_data, uint8_t *const *parity_ptrs, size_t m_parity, size_t block_size);
int32_t ttzip_rust_rs_decode(const uint8_t *const *available_ptrs, const int32_t *available_indices, size_t num_available, size_t k_data, size_t m_parity, const int32_t *missing_indices, size_t num_missing, uint8_t *const *reconstructed_ptrs, size_t block_size);
int32_t ttzip_rust_rs_create_recovery_record(const uint8_t *payload, size_t payload_len, double redundancy_percent, size_t slice_size, uint8_t **out_record, size_t *out_record_len);
int32_t ttzip_rust_rs_repair_archive(const char *archive_path, bool *out_repaired);
void ttzip_rust_rs_free_buffer(uint8_t *ptr, size_t len);

/**
 * Archive Standards & Magic Signatures Format Sniffing & Compliance
 */
TTZipStatus ttzip_rust_detect_format_buffer(const uint8_t *buf, size_t len, const char *filename_hint, int32_t *out_format, bool *out_is_sfx, size_t *out_sfx_offset);
TTZipStatus ttzip_rust_detect_format_file(const char *file_path, int32_t *out_format, bool *out_is_sfx, size_t *out_sfx_offset);
TTZipStatus ttzip_rust_check_compliance_buffer(const uint8_t *buf, size_t len, int32_t format_hint, char **out_report_json, bool *out_is_compliant);
TTZipStatus ttzip_rust_check_compliance_file(const char *file_path, char **out_report_json, bool *out_is_compliant);
void ttzip_rust_free_compliance_report(char *report_ptr);

/**
 * DEFLATE / zlib / gzip Codecs (libdeflate)
 */
TTZipStatus ttzip_rust_deflate_compress(const uint8_t *src, size_t src_len, uint8_t *dst, size_t dst_capacity, int32_t level, size_t *out_len);
TTZipStatus ttzip_rust_deflate_decompress(const uint8_t *src, size_t src_len, uint8_t *dst, size_t dst_capacity, size_t *out_len);
TTZipStatus ttzip_rust_zlib_compress(const uint8_t *src, size_t src_len, uint8_t *dst, size_t dst_capacity, int32_t level, size_t *out_len);
TTZipStatus ttzip_rust_zlib_decompress(const uint8_t *src, size_t src_len, uint8_t *dst, size_t dst_capacity, size_t *out_len);
TTZipStatus ttzip_rust_gzip_compress(const uint8_t *src, size_t src_len, uint8_t *dst, size_t dst_capacity, int32_t level, size_t *out_len);
TTZipStatus ttzip_rust_gzip_decompress(const uint8_t *src, size_t src_len, uint8_t *dst, size_t dst_capacity, size_t *out_len);
size_t ttzip_rust_deflate_compress_bound(size_t src_len, int32_t level);

/**
 * Zstandard Codec (zstd)
 */
TTZipStatus ttzip_rust_zstd_compress(const uint8_t *src, size_t src_len, uint8_t *dst, size_t dst_capacity, int32_t level, size_t *out_len);
TTZipStatus ttzip_rust_zstd_compress_advanced(
    const uint8_t *src,
    size_t src_len,
    uint8_t *dst,
    size_t dst_capacity,
    int32_t level,
    uint32_t nb_workers,
    uint32_t job_size_mb,
    uint32_t overlap_log,
    uint32_t window_log,
    bool enable_ldm,
    size_t *out_len
);
TTZipStatus ttzip_rust_zstd_decompress(const uint8_t *src, size_t src_len, uint8_t *dst, size_t dst_capacity, size_t *out_len);
size_t ttzip_rust_zstd_compress_bound(size_t src_len);
uint64_t ttzip_rust_zstd_get_decompressed_size(const uint8_t *src, size_t src_len);

/**
 * Fast-LZMA2 Codec (fast-lzma2)
 */
TTZipStatus ttzip_rust_fl2_compress(const uint8_t *src, size_t src_len, uint8_t *dst, size_t dst_capacity, int32_t level, uint32_t nb_threads, size_t *out_len);
TTZipStatus ttzip_rust_fl2_decompress(const uint8_t *src, size_t src_len, uint8_t *dst, size_t dst_capacity, uint32_t nb_threads, size_t *out_len);
size_t ttzip_rust_fl2_compress_bound(size_t src_len);
uint64_t ttzip_rust_fl2_find_decompressed_size(const uint8_t *src, size_t src_len);

/**
 * Fast Block Codecs (LZ4, Snappy, Apple LZFSE)
 */
TTZipStatus ttzip_rust_lz4_compress(const uint8_t *src, size_t src_len, uint8_t *dst, size_t dst_capacity, size_t *out_len);
TTZipStatus ttzip_rust_lz4_decompress(const uint8_t *src, size_t src_len, uint8_t *dst, size_t dst_capacity, size_t *out_len);
size_t ttzip_rust_lz4_compress_bound(size_t src_len);

TTZipStatus ttzip_rust_snappy_compress(const uint8_t *src, size_t src_len, uint8_t *dst, size_t dst_capacity, size_t *out_len);
TTZipStatus ttzip_rust_snappy_decompress(const uint8_t *src, size_t src_len, uint8_t *dst, size_t dst_capacity, size_t *out_len);
size_t ttzip_rust_snappy_max_compressed_length(size_t src_len);
TTZipStatus ttzip_rust_snappy_uncompressed_length(const uint8_t *src, size_t src_len, size_t *out_len);
bool ttzip_rust_snappy_validate(const uint8_t *src, size_t src_len);

TTZipStatus ttzip_rust_lzfse_compress(const uint8_t *src, size_t src_len, uint8_t *dst, size_t dst_capacity, size_t *out_len);
TTZipStatus ttzip_rust_lzfse_decompress(const uint8_t *src, size_t src_len, uint8_t *dst, size_t dst_capacity, size_t *out_len);

/**
 * Charset Detector (Mozilla uchardet)
 */
TTZipStatus ttzip_rust_detect_charset(const uint8_t *data, size_t data_len, char *out_buf, size_t out_buf_capacity);

/**
 * Stream Adapters & Micro-buffering
 */
typedef struct TTZipStreamReaderHandle TTZipStreamReaderHandle;
typedef struct TTZipStreamWriterHandle TTZipStreamWriterHandle;

TTZipStreamReaderHandle *ttzip_rust_stream_reader_new_file(const char *path, size_t buffer_size);
int32_t ttzip_rust_stream_reader_read(TTZipStreamReaderHandle *handle, const uint8_t **out_ptr, size_t *out_len);
void ttzip_rust_stream_reader_free(TTZipStreamReaderHandle *handle);

TTZipStreamWriterHandle *ttzip_rust_stream_writer_new_file(const char *path, size_t buffer_size);
int32_t ttzip_rust_stream_writer_write(TTZipStreamWriterHandle *handle, const uint8_t *data, size_t len);
int32_t ttzip_rust_stream_writer_flush(TTZipStreamWriterHandle *handle);
void ttzip_rust_stream_writer_free(TTZipStreamWriterHandle *handle);

/**
 * Filesystem Security & APFS Optimizations
 */
TTZipStatus ttzip_rust_validate_path(const char *dest_dir, const char *entry_path, char *out_sanitized, size_t out_capacity);
int32_t ttzip_rust_apfs_preallocate(int32_t fd, int64_t target_size);
int32_t ttzip_rust_apfs_clone_file(const char *src, const char *dst, bool overwrite);
int32_t ttzip_rust_apfs_clone_range(int32_t in_fd, int32_t out_fd);
bool ttzip_rust_is_mac_junk(const char *path);
int32_t ttzip_rust_remove_path_fast(const char *path);

/**
 * Runtime Cancellation & Structured Logging
 */
typedef struct TTZipCancellationToken TTZipCancellationToken;

TTZipCancellationToken *ttzip_rust_cancellation_token_new(void);
void ttzip_rust_cancellation_token_cancel(TTZipCancellationToken *token, uint8_t reason);
bool ttzip_rust_cancellation_token_is_cancelled(const TTZipCancellationToken *token);
void ttzip_rust_cancellation_token_free(TTZipCancellationToken *token);

typedef void (*TTZipLogCallback)(TTZipLogLevel level, const char *target_module, const char *message, const char *file, int32_t line, void *user_data);

TTZipStatus ttzip_rust_set_logger(TTZipLogCallback callback, TTZipLogLevel min_level, void *user_data);
void ttzip_rust_log(TTZipLogLevel level, const char *target, const char *message, const char *file, int32_t line);

/**
 * Unified High-Level Archive Operations
 */
TTZipStatus ttzip_rust_inspect_archive(
    const char *archive_path,
    const char *password,
    bool detect_encoding,
    TTZipInspectCallback callback,
    void *user_data
);

TTZipStatus ttzip_rust_extract_archive(
    const char *archive_path,
    const char *destination_path,
    const TTZipExtractOptions *options
);

TTZipStatus ttzip_rust_create_archive(
    const char *const *source_paths,
    size_t source_count,
    const char *destination_path,
    const TTZipCreateOptions *options
);

/**
 * Pure Rust TAR & ZIP Direct C-ABI Operations
 */
TTZipStatus ttzip_rust_tar_scan_entries(
    const char *archive_path,
    TTZipInspectCallback callback,
    void *user_data
);

TTZipStatus ttzip_rust_tar_extract_entry(
    const char *archive_path,
    size_t entry_index,
    uint8_t *out_buffer,
    size_t buffer_capacity,
    size_t *out_extracted_len
);

TTZipStatus ttzip_rust_zip_scan_entries(
    const char *archive_path,
    TTZipInspectCallback callback,
    void *user_data
);

#ifdef __cplusplus
}
#endif

#endif /* TTZIP_RUST_GLUE_H */

