// SPDX-License-Identifier: LicenseRef-TTZip-Source-Available-1.0
//
// Copyright (c) 2026 Witt Kung <witt.w.kung@gmail.com>
// All rights reserved.
//
// TTZip: High-performance native archiving and compression engine for macOS.

import Foundation

extension ShellCompletionGenerator {
    /// 生成 Zsh `_arguments` 自动补全脚本
    public static func generateZsh(binaryName: String = "ttzip-cli", includeAliases: Bool = true) -> String {
        var out = "#compdef \(binaryName)\n\n"
        out += "# Zsh completion script for \(binaryName)\n"
        out += "# Auto-generated by TTZip ShellCompletionGenerator\n\n"
        
        let subcommands = CLICommandSpec.subcommands
        let globalOptions = CLICommandSpec.globalOptions
        
        out += "_\(binaryName.replacingOccurrences(of: "-", with: "_"))() {\n"
        out += "    local curcontext=\"$curcontext\" state line\n"
        out += "    typeset -A opt_args\n\n"
        
        out += "    local -a global_opts\n"
        out += "    global_opts=(\n"
        for opt in globalOptions {
            let desc = opt.description.replacingOccurrences(of: "'", with: "''").replacingOccurrences(of: "\"", with: "\\\"")
            if let short = opt.shortName {
                if opt.takesValue {
                    let valName = opt.valueName ?? "VALUE"
                    out += "        '(-\(short) --\(opt.longName))'{\\-\(short),--\(opt.longName)}\"[\(desc)]: :\(valName)\"\n"
                } else {
                    out += "        '(-\(short) --\(opt.longName))'{\\-\(short),--\(opt.longName)}\"[\(desc)]\"\n"
                }
            } else {
                if opt.takesValue {
                    let valName = opt.valueName ?? "VALUE"
                    out += "        '--\(opt.longName)[\(desc)]: :\(valName)'\n"
                } else {
                    out += "        '--\(opt.longName)[\(desc)]'\n"
                }
            }
        }
        out += "    )\n\n"
        
        out += "    _arguments -C \\\n"
        out += "        \"$global_opts[@]\" \\\n"
        out += "        '1: :->command' \\\n"
        out += "        '*:: :->args' && return 0\n\n"
        
        out += "    case $state in\n"
        out += "        command)\n"
        out += "            local -a subcommands\n"
        out += "            subcommands=(\n"
        for sub in subcommands {
            let desc = sub.summary.replacingOccurrences(of: "'", with: "''")
            out += "                '\(sub.name):\(desc)'\n"
            if includeAliases {
                for alias in sub.aliases {
                    out += "                '\(alias):Alias for \(sub.name)'\n"
                }
            }
        }
        out += "            )\n"
        out += "            _describe -t commands '\(binaryName) command' subcommands\n"
        out += "            ;;\n"
        out += "        args)\n"
        out += "            case $words[1] in\n"
        for sub in subcommands {
            let names = ([sub.name] + (includeAliases ? sub.aliases : [])).joined(separator: "|")
            out += "                \(names))\n"
            if sub.name == "completion" {
                out += "                    _arguments -C \\\n"
                out += "                        '1:shell:(zsh bash fish nushell)'\n"
            } else {
                out += "                    local -a sub_opts\n"
                out += "                    sub_opts=(\n"
                for opt in sub.options {
                    let desc = opt.description.replacingOccurrences(of: "'", with: "''").replacingOccurrences(of: "\"", with: "\\\"")
                    if let short = opt.shortName {
                        if opt.takesValue {
                            let valName = opt.valueName ?? "VALUE"
                            if !opt.valueChoices.isEmpty {
                                let choices = opt.valueChoices.joined(separator: " ")
                                out += "                        '(-\(short) --\(opt.longName))'{\\-\(short),--\(opt.longName)}\"[\(desc)]: :(\(choices))\"\n"
                            } else {
                                out += "                        '(-\(short) --\(opt.longName))'{\\-\(short),--\(opt.longName)}\"[\(desc)]: :\(valName)\"\n"
                            }
                        } else {
                            out += "                        '(-\(short) --\(opt.longName))'{\\-\(short),--\(opt.longName)}\"[\(desc)]\"\n"
                        }
                    } else {
                        if opt.takesValue {
                            let valName = opt.valueName ?? "VALUE"
                            if !opt.valueChoices.isEmpty {
                                let choices = opt.valueChoices.joined(separator: " ")
                                out += "                        '--\(opt.longName)[\(desc)]: :(\(choices))'\n"
                            } else {
                                out += "                        '--\(opt.longName)[\(desc)]: :\(valName)'\n"
                            }
                        } else {
                            out += "                        '--\(opt.longName)[\(desc)]'\n"
                        }
                    }
                }
                out += "                    )\n"
                out += "                    _arguments \\\n"
                out += "                        \"$global_opts[@]\" \\\n"
                out += "                        \"$sub_opts[@]\" \\\n"
                out += "                        '*:files:_files'\n"
            }
            out += "                    ;;\n"
        }
        out += "                *)\n"
        out += "                    _files\n"
        out += "                    ;;\n"
        out += "            esac\n"
        out += "            ;;\n"
        out += "    esac\n"
        out += "}\n\n"
        out += "_\(binaryName.replacingOccurrences(of: "-", with: "_")) \"$@\"\n"
        return out
    }
}
