// SPDX-License-Identifier: LicenseRef-TTZip-Source-Available-1.0
//
// Copyright (c) 2026 Witt Kung <witt.w.kung@gmail.com>
// All rights reserved.
//
// TTZip: High-performance native archiving and compression engine for macOS.

import Foundation

extension ShellCompletionGenerator {
    /// 生成 Bash `complete -F` 自动补全脚本
    public static func generateBash(binaryName: String = "ttzip-cli", includeAliases: Bool = true) -> String {
        let fnName = "_\(binaryName.replacingOccurrences(of: "-", with: "_"))_completions"
        var out = "# Bash completion for \(binaryName)\n"
        out += "# Auto-generated by TTZip ShellCompletionGenerator\n\n"
        out += "\(fnName)() {\n"
        out += "    local cur prev cword\n"
        if true {
            out += "    if type -t _init_completion >/dev/null 2>&1; then\n"
            out += "        _init_completion || return\n"
            out += "    else\n"
            out += "        cur=\"${COMP_WORDS[COMP_CWORD]}\"\n"
            out += "        prev=\"${COMP_WORDS[COMP_CWORD-1]}\"\n"
            out += "        cword=$COMP_CWORD\n"
            out += "    fi\n\n"
        }
        
        let subcommands = CLICommandSpec.subcommands
        let globalOptions = CLICommandSpec.globalOptions
        
        var allCmds: [String] = []
        for sub in subcommands {
            allCmds.append(sub.name)
            if includeAliases {
                allCmds.append(contentsOf: sub.aliases)
            }
        }
        let cmdsStr = allCmds.joined(separator: " ")
        var globalFlags: [String] = []
        for opt in globalOptions {
            if let s = opt.shortName { globalFlags.append("-\(s)") }
            globalFlags.append("--\(opt.longName)")
        }
        let globalFlagsStr = globalFlags.joined(separator: " ")
        
        out += "    local commands=\"\(cmdsStr)\"\n"
        out += "    local global_options=\"\(globalFlagsStr)\"\n\n"
        out += "    if [ \"$cword\" -eq 1 ]; then\n"
        out += "        COMPREPLY=( $(compgen -W \"$commands $global_options\" -- \"$cur\") )\n"
        out += "        return 0\n"
        out += "    fi\n\n"
        out += "    local cmd=\"${COMP_WORDS[1]}\"\n"
        out += "    case \"$cmd\" in\n"
        for sub in subcommands {
            let names = ([sub.name] + (includeAliases ? sub.aliases : [])).joined(separator: "|")
            var subFlags: [String] = []
            for opt in sub.options {
                if let s = opt.shortName { subFlags.append("-\(s)") }
                subFlags.append("--\(opt.longName)")
            }
            let subFlagsStr = subFlags.joined(separator: " ")
            out += "        \(names))\n"
            if sub.name == "completion" {
                out += "            if [ \"$cword\" -eq 2 ]; then\n"
                out += "                COMPREPLY=( $(compgen -W \"zsh bash fish nushell\" -- \"$cur\") )\n"
                out += "                return 0\n"
                out += "            fi\n"
            } else if !subFlags.isEmpty {
                out += "            if [[ \"$cur\" == -* ]]; then\n"
                out += "                COMPREPLY=( $(compgen -W \"\(subFlagsStr) $global_options\" -- \"$cur\") )\n"
                out += "                return 0\n"
                out += "            fi\n"
            }
            out += "            ;;\n"
        }
        out += "        *)\n"
        out += "            ;;\n"
        out += "    esac\n\n"
        out += "    COMPREPLY=( $(compgen -f -- \"$cur\") )\n"
        out += "}\n\n"
        out += "complete -F \(fnName) \(binaryName)\n"
        return out
    }
    
    /// 生成 Fish `complete -c` 自动补全脚本
    public static func generateFish(binaryName: String = "ttzip-cli", includeAliases: Bool = true) -> String {
        var out = "# Fish completion for \(binaryName)\n"
        out += "# Auto-generated by TTZip ShellCompletionGenerator\n\n"
        out += "# Disable file completion by default for commands\n"
        out += "complete -c \(binaryName) -f\n\n"
        
        let subcommands = CLICommandSpec.subcommands
        let globalOptions = CLICommandSpec.globalOptions
        
        out += "# Global options\n"
        for opt in globalOptions {
            var line = "complete -c \(binaryName)"
            if let short = opt.shortName {
                line += " -s \(short)"
            }
            line += " -l \(opt.longName)"
            if opt.takesValue {
                line += " -r"
            }
            line += " -d \"\(opt.description.replacingOccurrences(of: "\"", with: "\\\""))\""
            out += "\(line)\n"
        }
        out += "\n# Subcommands\n"
        for sub in subcommands {
            out += "complete -c \(binaryName) -n \"__fish_use_subcommand\" -a \"\(sub.name)\" -d \"\(sub.summary.replacingOccurrences(of: "\"", with: "\\\""))\"\n"
            if includeAliases {
                for alias in sub.aliases {
                    out += "complete -c \(binaryName) -n \"__fish_use_subcommand\" -a \"\(alias)\" -d \"Alias for \(sub.name)\"\n"
                }
            }
        }
        out += "\n# Subcommand-specific options\n"
        for sub in subcommands {
            guard !sub.options.isEmpty else { continue }
            let allNames = ([sub.name] + (includeAliases ? sub.aliases : [])).joined(separator: " ")
            let condition = "__fish_seen_subcommand_from \(allNames)"
            for opt in sub.options {
                var line = "complete -c \(binaryName) -n \"\(condition)\""
                if let short = opt.shortName {
                    line += " -s \(short)"
                }
                line += " -l \(opt.longName)"
                if opt.takesValue {
                    line += " -r"
                }
                if !opt.valueChoices.isEmpty {
                    line += " -a \"\(opt.valueChoices.joined(separator: " "))\""
                }
                line += " -d \"\(opt.description.replacingOccurrences(of: "\"", with: "\\\""))\""
                out += "\(line)\n"
            }
        }
        out += "\n# Enable file completions for archive arguments\n"
        let fileCmds = subcommands.filter { $0.name != "completion" && $0.name != "man" }
        var allFileCmdNames: [String] = []
        for c in fileCmds {
            allFileCmdNames.append(c.name)
            if includeAliases {
                allFileCmdNames.append(contentsOf: c.aliases)
            }
        }
        out += "complete -c \(binaryName) -n \"__fish_seen_subcommand_from \(allFileCmdNames.joined(separator: " "))\" -F\n"
        out += "complete -c \(binaryName) -n \"__fish_seen_subcommand_from completion\" -a \"zsh bash fish nushell\" -d \"Target shell\"\n"
        return out
    }
    
    /// 生成 Nushell `export extern` 自动补全脚本
    public static func generateNushell(binaryName: String = "ttzip-cli", includeAliases: Bool = true) -> String {
        var out = "# Nushell completion for \(binaryName)\n"
        out += "# Auto-generated by TTZip ShellCompletionGenerator\n\n"
        
        let subcommands = CLICommandSpec.subcommands
        let globalOptions = CLICommandSpec.globalOptions
        
        // Root command extern
        out += "export extern \"\(binaryName)\" [\n"
        for opt in globalOptions {
            let shortPart = opt.shortName.map { "(-\($0))" } ?? ""
            let typePart: String
            if opt.takesValue {
                let v = opt.valueName ?? ""
                if v == "NUM" || v == "N" {
                    typePart = ": int"
                } else if v == "PATH" || v == "FILE" || v == "DIR" {
                    typePart = ": path"
                } else {
                    typePart = ": string"
                }
            } else {
                typePart = ""
            }
            out += "    --\(opt.longName)\(shortPart)\(typePart)  # \(opt.description)\n"
        }
        out += "]\n\n"
        
        // Subcommands externs
        for sub in subcommands {
            let allNames = [sub.name] + (includeAliases ? sub.aliases : [])
            for name in allNames {
                out += "export extern \"\(binaryName) \(name)\" [\n"
                for opt in sub.options {
                    let shortPart = opt.shortName.map { "(-\($0))" } ?? ""
                    let typePart: String
                    if opt.takesValue {
                        let v = opt.valueName ?? ""
                        if v == "NUM" || v == "N" {
                            typePart = ": int"
                        } else if v == "PATH" || v == "FILE" || v == "DIR" {
                            typePart = ": path"
                        } else {
                            typePart = ": string"
                        }
                    } else {
                        typePart = ""
                    }
                    out += "    --\(opt.longName)\(shortPart)\(typePart)  # \(opt.description)\n"
                }
                if sub.name == "completion" {
                    out += "    shell?: string  # Target shell (zsh, bash, fish, nushell)\n"
                } else {
                    out += "    ...rest: string  # Target files or directories\n"
                }
                out += "]\n\n"
            }
        }
        return out
    }
}
